### PR TITLE
#161254651 Integrate Travis CI with README badge

### PR DESCRIPTION
**Pull request by evamaina**
#### What does this PR do?
* This PR integrates Travis CI badge with README badge.
#### Description of Task to be completed?
* Add Travis badge to the README file
* Create a .travis.yml file in the project folder

#### How should this be manually tested?
* Open the repo : git clone https://github.com/andela/ah-orcas.git
* switch to integrate-Travis branch
* Check the README file

#### Any background context you want to provide?
* Travis makes working in a team for a software project easier with automated builds which  are triggered automatically when each developer checks in their code to the repository.
* It also helps  to automatically run tests and other preliminary build steps

#### What are the relevant pivotal tracker stories?
[#161254651](https://www.pivotaltracker.com/story/show/161254651)
#### Screenshots
screen shot 2018-10-23 at 12 29 04

### CODE REVIEW

**Comment by code-sleuth** [comment]
`What are the relevant pivotal tracker stories?` should be in the format `#pt-board-id`

**Comment by evamaina** [comment]
> `What are the relevant pivotal tracker stories?` should be in the format `#pt-board-id`

Hi Ibrahim, kindly clarify because I have already put the pt-board-id in the PR

**Comment by code-sleuth** [comment]
The `#` is missing.

**Comment by evamaina** [comment]
> The `#` is missing.

Added. Thanks

**Comment by evamaina** [comment]
.

**Pull request closed without merging**
