### PR TITLE
#161254667 like and dislike article

### PR DESCRIPTION
**Pull request by abadojack**
#### What does this PR do?
```Returns the likes and dislikes during articles listing```

#### Description of Task to be completed?
```The number of likes and dislikes are be included in the model returned  during article listing```
```Return number of comments during article listing```

#### How should this be manually tested?
- Clone this repo.
``` 
$ git clone https://github.com/andela/ah-orcas.git
```
- Navigate to this branch.
``` 
$ git checkout  ft-like-dislike-article-161254667
```
- create a python virtual environment in your local machine and start it.
```code
$ virtualenv env
$ source env/bin/activate
```
- Create a .env file and run it. Check sample.env file to configure yours.
```
$ source .env
```
- Run the app
```
$ python manage.py runserver
```
- Test the endpoint to see if it returns likes/dislikes
```
GET api/article/
```

#### What are the relevant pivotal tracker stories?
 [#161254667](https://www.pivotaltracker.com/story/show/161254667)

### CODE REVIEW

**Review by TheSteelGuy — APPROVED** [review]
LGTM

**Review by wrotich — APPROVED** [review]
LGTM

**Review by Eyansky — APPROVED** [review]
LTGM

**Comment by code-sleuth** [comment]
include screenshots of the work done

**Pull request merged**
