### PR TITLE
#161254673 tag articles

### PR DESCRIPTION
**Pull request by abadojack**
#### What does this PR do?
    This PR allows users to add tags to articles
#### Description of Task to be completed?
    A user should be able to add tags to articles that they create
#### How should this be manually tested?
- Clone this repo.
``` 
$ git clone https://github.com/andela/ah-orcas.git
```
- Switch to this branch
``` 
$  git checkout  ft-article-comments-161254665
```
- Create a .env file and run it. Check sample.env file to configure yours.
```
$ source .env
```
- Run the app
```
$ python manage.py runserver
```
- Create an article using Postman: http://localhost:8000/api/article/create/
- Test the endpoint using Postman:
  endpoint: http://localhost:8000/api/article/tag/article-slug
  body: 
```
 {
   "article":{
      "tags":[
         "train",
         "dragon"
      ]
   }
}
```
#### Any background context you want to provide?
    Tagging refers to the metadata that is assigned to a piece of content by the content creator and the readers/users of the content. 
    Tagging allows for organization and or categorization of content.
#### What are the relevant pivotal tracker stories?
[#161254673](https://www.pivotaltracker.com/story/show/161254673)

### CODE REVIEW

**Comment by abadojack** [comment]
@TheSteelGuy I fixed the failing tests

**Comment by wrotich** [comment]
@abadojack please check on how to test manually, has some errors, there is a typo in the url hence won't work when someone is following the instructions given. The url given ```http://localhost:8000/api/article/**tags**/article-slug**/**``` takes tags and a backslash but in the code the url takes tag and no backslash. Check on that.

**Comment by TheSteelGuy** [comment]
Awesome @abadojack

**Comment by abadojack** [comment]
@wrotich I have made the changes you requested

**Comment by Eyansky** [comment]
LGTM but in the description for next time, I think it would be better to create a collection on postman and share it instead of writing the endpoints manually.

**Pull request merged**
