### PR TITLE
#161472787 integrate codacy

### PR DESCRIPTION
**Pull request by abadojack**
What does this PR do?

    This PR integrates codacy by adding a configuration file

Description of Task to be completed?

    Add codacy configuration file

How should this be manually tested?

    Check PRs for automated codacy reviews

Any background context you want to provide?

    Codacy automates code reviews and monitors code quality over time. Static analysis, code coverage and metrics for Python.

What are the relevant pivotal tracker stories?

[#161472787](https://www.pivotaltracker.com/story/show/161472787)

### CODE REVIEW

**Comment by kipropbrian** [comment]
You can just ask for permission @abadojack from @evamaina and you will be admin

**Comment by abadojack** [comment]
@kipropbrian @wrotich I am an admin already

**Comment by kipropbrian** [comment]
It seems that codacy needs access to the andela organization in order to work properly. I will have to consult with technology to see if this is possible. If not we will have to abandon codacy. 😢

**Comment by kipropbrian** [comment]
Killing this as codeclimate is now working @abadojack @code-sleuth

**Pull request closed without merging**
